name: .NET CI/CD - NuGet Publish

on:
  push:
    branches: [master]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.calc-version.outputs.version }}  # Define output for this job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Calculate version
        id: calc-version
        uses: julianghionoiu/semver-action@v1
        with:
          version-file: './nupkgs/*.nupkg'
          version-increment: 'patch'

      - name: Update version in csproj
        run: |
          sed -i 's|<Version>.*</Version>|<Version>${{ steps.calc-version.outputs.version }}</Version>|g' ./LoggingStandards/CerberusClientLogging.csproj

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack
        run: dotnet pack --no-restore --verbosity normal --output ./nupkgs --configuration Release

      - name: Push to NuGet
        id: nuget-push
        run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate

      - name: Check NuGet Push Result
        run: |
          if [ ${{ steps.nuget-push.exit-code }} -ne 0 ]; then
            echo "NuGet package push failed."
            exit 1
          fi
